### ISSUE TITLE
ModuleNotFoundError: No module named 'django.contrib.staticfiles.templatetags'

### ISSUE THREAD

**Issue by dtcooper** [MaistrenkoAnton/django-material-admin#50]
Per [this comment](https://docs.djangoproject.com/en/3.0/releases/3.0/#features-removed-in-3-0) in Django 3's release notes, `django.contrib.staticfiles.templatetags.staticfiles.static()` has been removed. Therefore, when run under Django 3's RC release, I get the following error:

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/utils/module_loading.py", line 44, in autodiscover_modules
    if register_to:
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 537, in _setup
    AdminSiteClass = import_string(apps.get_app_config('admin').default_site)
  File "/usr/local/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/material/admin/sites.py", line 9, in <module>
    from material.admin.settings import MATERIAL_ADMIN_SITE
  File "/usr/local/lib/python3.8/site-packages/material/admin/settings.py", line 2, in <module>
    from django.contrib.staticfiles.templatetags.staticfiles import static as staticfiles
ModuleNotFoundError: No module named 'django.contrib.staticfiles.templatetags'
```

Thanks!

**Comment by MaistrenkoAnton** [comment]
Thanks, Fixed in `v1.6.6`
