### ISSUE TITLE
1.6.* throwing django error on runserver

### ISSUE THREAD

**Issue by h3adHunter** [MaistrenkoAnton/django-material-admin#57]
Hi Anton, im trying to update my django-material-admin version from 1.5.1 to 1.6.10.

The steps were: 

- install the newest version with pip.
- added material.admin and material.admin.default to INSTALLED_APPS setting instead of django.contrib.admin into my settings.py file
- add the path('admin/', admin.site.urls), to urlpatterns in my urls.py file
- change the imports from **material.admin.decorators or options** to **django.contrib.admin** import ModelAdmin, register into my admin.py files.

When i hit the command **python manage.py runserver** the error im getting is the following: 

Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/django/template/utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/django/contrib/admin/checks.py", line 79, in check_dependencies
    for engine in engines.all():
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/django/template/utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/django/template/utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/django/template/utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/django/template/backends/django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/django/template/backends/django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/django/template/backends/django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/j0t4/Desktop/gaia/proyectos-externos/donde-comemos/donde-comemos-be/lib/python3.5/site-packages/material/admin/templatetags/material.py", line 43
    return mark_safe(f"""<td class="field-{field_name}">
              <label for="id_{name[0]}" class="checkbox-block">
                <input class="action-select" name="{name[0]}" id="id_{name[0]}" type="checkbox" {checked}>
                <span></span>
              </label>
            </td>""")
 
                   ^
SyntaxError: invalid syntax

Same thing is happening with 1.6.9.

Regards!

**Comment by MaistrenkoAnton** [comment]
Hi, hard to say the reason of error.
In case you put the `django.contrib.admin` instead of `material.admin` and `material.admin.default`. Does it work ?

**Comment by pablop94** [comment]
Hi, the issue is because python version is lower than 3.6, if the project is intended to work with 3.4+ it should work. It's using 3.6 f strings.

To be compatible with older python versions, the code must be something like this:
return mark_safe("""<td class="field-{field_name}">
              <label for="id_{name}" class="checkbox-block">
                <input class="action-select" name="{name}" id="id_{name}" type="checkbox" {checked}>
                <span></span>
              </label>
            </td>""".format(field_name=field_name, name=name[0], checked=checked)

**Comment by pablop94** [comment]
I've created pull request #58

**Comment by MaistrenkoAnton** [comment]
Hi, thanks!
Applied in `v1.6.11`
